# Generated by Django 4.2.17 on 2024-12-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=django.db.models.deletion.SET_NULL, null=True, upload_to='post_images/'),
        ),
    ]
