# Generated by Django 4.2.17 on 2024-12-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_been_edited',
            field=models.BooleanField(default=False),
        ),
    ]
