# Generated by Django 4.2.17 on 2024-12-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_approved_post_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('approve_posts', 'Can approve posts'), ('delete_posts', 'Can delete user posts')]},
        ),
    ]
