# Generated by Django 4.2.16 on 2024-11-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workout_creator_alter_workouthistory_user'),
        ('meals', '0004_alter_meal_creator_alter_mealhistory_user'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
