# Generated by Django 4.2.17 on 2024-12-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_picture/default_pfp.jpg', upload_to='profile_picture/users'),
        ),
    ]
