# Generated by Django 4.2.17 on 2024-12-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_date_of_birth_profile_age_profile_bmr'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
