# Generated by Django 4.2.17 on 2024-12-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bmr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
