# Generated by Django 4.2.17 on 2024-12-09 11:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_alter_profile_bmr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='MealHistory',
        ),
    ]
