# Generated by Django 4.2.17 on 2024-12-09 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_alter_profile_bmr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealhistory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bmr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
