# Generated by Django 4.2.17 on 2024-12-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'permissions': [('edit_base_meals', 'Can edit base meals')]},
        ),
    ]
