# Generated by Django 4.2.16 on 2024-11-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('meals', '0002_alter_meal_calories_alter_meal_carbs_alter_meal_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),

    ]
